application: politicfight
version: 1
runtime: python27
api_version: 1
threadsafe: yes
handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /indexns
  static_files: indexns.html
  upload: indexns.html
- url: /editor
  static_files: editor.html
  upload: editor.html
- url: /xmlparser2
  static_files: xmlparser2.html
  upload: xmlparser2.html  
- url: /sourcecode
  static_dir: sourcecode
- url: /classes
  static_dir: classes
- url: /img
  static_dir: img
- url: /data
  static_dir: data
- url: /sounds
  static_dir: sounds
- url: /lib
  static_dir: lib
- url: /framework
  static_dir: framework

libraries:
- name: webapp2
  version: "2.5.1"